### ISSUE TITLE
"&&" in simple value in endpoint property cannot be saved 

### ISSUE THREAD

**Issue by mvweerd** [assimbly/gateway#629]
a File Filter containing more than one condition cannot be saved:
For example: ${file:size} < 30000000 && ${file:modified} < ${date:now-24h}

**Comment by assimbly** [comment]
I checked it and I turned out that the option with double && is saved, but not shown in the user interface afterwards. This is because on the background Camel uses the '&' to separate options. For example:

option1=value1&option2=value2&option3=value3

Normally, simple expression aren't used in options, so this is somewhat of an edge case. I try to work around it with regex that ignore multiple occurrences of &. This can be check in 3.6.0 beta1 when released.
