### ISSUE TITLE
Question: how to set the correct data type (hex/byte?) for a JMS_IBM_MQMD header

### ISSUE THREAD

**Issue by petervdz** [assimbly/gateway#691]
We need to set the JMSMessageID for IBM MQ in the messages for a specific flow. To do this, we fill the JMS_IBM_MQMD_MsgId (see xml below) in a route - but when sending the message to IBM MQ it returns an error: JMSCC0051: The property 'JMS_IBM_MQMD_MsgId' should be set using type '[B', not 'java.lang.String'. How to do it properly?

Example code:
*        <setHeader name="JMS_IBM_MQMD_MsgId">
*                <header>DTIMessageID</header>
*        </setHeader>

**Comment by assimbly** [comment]
@petervdz 

1. It's uncommon to set the JMS MessageID manually:

https://stackoverflow.com/questions/23299147/how-to-set-jmsmessageid-and-jmscorrelationid-properly

So normally this ID is set by Camel/Assimbly. There are a few options to work with MessageID (https://camel.apache.org/components/3.14.x/jms-component.html). The IBMMQ component is based on the Camel JMS Component.

2. Setting the type of an header:

Generally, you can set the result type of a header like this:

  <setHeader headerName="myKey">
    <simple resultType="java.lang.String">myValue</simple>
   </setHeader>
   
   As a byte array:
       
  <setHeader headerName="myKey">
    <simple resultType="byte[]">myValue</simple>
   </setHeader>
   
   or from a header

  <setHeader headerName="myKey">
    <simple resultType="byte[]">${header.someKey}</simple>
   </setHeader> 
    
    
  3)   Also note that it sometimes tricky to connect to IBMMQ (it's more extensive than most MQ's). I once need to set a HEX literally (because it needed a HEX in EBCDIC)

**Comment by assimbly** [comment]
p.s. I could discuss this with @tomosjut when needed (because I now don't have a IBMMQ instance to test).

**Comment by petervdz** [comment]
Hi Raymond, I know it's uncommon to want to set the JMSMessageID, but in this case it's neccesary (temporary) because our integration platform is put in between an existing chain to be able to fase out some old legacy. I will try the code-suggestions! And @tomosjut is now on a holiday but will be back soon! Regards, Peter.

**Comment by tomosjut** [comment]
It is indeed uncommon to set the JMSMessageID yourself. It even goes against JMS specifications. But it is possible to set your own JMSMessageID. There are a few things to take in account:

- You can use the header JMS_IBM_MQMD_MsgId. The required type of this header is byte[]. So you should convert your JMSMessageID to byte[]
- The MsgId (corresponding with JMSMessageID) is a byte string that is of fixed size (24 bytes). You probably have a JMSMessageID that looks like this: "ID:c4c3c2...". Simply translating this string to byte[] won't work, because it will convert each individual character to a byte value. Therefore you have to dissect the string and translate each hexadecimal value (c4, c3, c2) to hexadecimal byte: `byte b = (byte) Integer.parseInt("c4", 16);`
- JMS_IBM_MQMD_MsgId is not an accepted JMS header, so you need to tell your JMSComponent to include this header: `jmsComponent.setAllowAdditionalHeaders("JMS_IBM_MQMD_MsgId");`
- Finally, you need to tell the QueueManager to use your custom headers. This requires the parameter mdWriteEnabled to be true (default is false). You need to set this parameter on the endpoint. To do this, you can set the following header: `.setHeader("CamelJmsDestinationName").simple("queue:///{{ibmmq.destination}}?mdWriteEnabled=true")`

**Comment by skin27** [comment]
Closing as Thomas port this to Fuse.
